### PR TITLE
Implement extend, alloc_uninit

### PR DESCRIPTION
**Pull request by pczarn**
These methods allow allocation of contiguous memory (slices).

### CODE REVIEW

**Comment by SimonSapin** [comment]
I’m not super interested in maintaining this. Do you want to take over? I can give away the name on crates.io.

**Comment by pczarn** [comment]
@SimonSapin  You already gave access to @jonastepe, but I could take over, FWIW.

**Comment by pczarn** [comment]
I suggest you un-watch this repository. I'm interested in co-maintaining this library, because my project will use it.

**Comment by jonastepe** [comment]
I would be happy, if @pczarn started co-maintaining. I may learn a thing or two from him.

**Comment by pczarn** [comment]
@jonastepe please merge.
Please also add me in repository settings -> collaborators, and run `cargo owner --add pczarn`

**Comment by SimonSapin** [comment]
Added @pczarn to collaborators.

**Comment by pczarn** [comment]
@SimonSapin Thanks, but I need ownership to publish: `cargo owner --add pczarn`

**Comment by SimonSapin** [comment]
Done.

**Pull request merged**
